# This is a basic workflow to help you get started with Actions

name: BuildFirmware

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v4.4

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive

      # Runs the build command
      - name: Build using idf.py
        run: |
          . ${IDF_PATH}/export.sh
          idf.py build
          
      - name: Get short commit hash
        id: commit_sha
        run: echo "::set-output name=short::$(git rev-parse --short HEAD)"
      
      - name: Copy built files
        run: |
          cp build/bootloader/bootloader.bin bootloader.bin
          cp build/partition_table/partition_table.bin partition-table.bin
          cp build/main.bin main.bin

      - name: Create flashing instructions
        run: echo -e "# Flashing instructions\nTo flash the firmware onto your device you can use [esptool](https://github.com/espressif/esptool).\n\nUsing the following command arguments:\n```\n-p (PORT) -b 460800 --before default_reset --after hard_reset --chip esp32  write_flash --flash_mode dio --flash_size detect --flash_freq 40m 0x1000 bootloader.bin 0x8000 partition-table.bin 0x10000 main.bin\n```\n**!! Replace (PORT) with your device !!**" > flashing.md

      # Runs a set of commands using the runners shell
      - name: Upload build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build-${{steps.commit_sha.outputs.short}}
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/main.bin
            flashing.md
